### ISSUE TITLE
TypeError: channel.isDMBased is not a function

### ISSUE THREAD

**Issue by RyuuOsamu** [ItzDerock/discord-html-transcripts#112]
Hi, I get this error when executig the `Transcript.generateFromMessages() `  this is how i use it :
```
      const transcripts = await Transcript.generateFromMessages(
        interaction.channel,
        { limit: Amount }
      );
```
an this is the full error

```
C:\Users\ryuuo\Desktop\S.E.C.R.E.T\node_modules\discord-html-transcripts\dist\index.js:47
        callbacks: Object.assign({ resolveChannel: async (id) => channel.client.channels.fetch(id).catch(() => null), resolveUser: async (id) 
=> channel.client.users.fetch(id).catch(() => null), resolveRole: channel.isDMBased() ? () => null : async (id) => { var _a; return (_a = channel.guild) === null || _a === void 0 ? void 0 : _a.roles.fetch(id).catch(() => null); } }, ((_b = options.callbacks) !== null && _b !== void 0 ? _b : {})),
                                                                          ^

TypeError: channel.isDMBased is not a function
    at Object.generateFromMessages (C:\Users\ryuuo\Desktop\S.E.C.R.E.T\node_modules\discord-html-transcripts\dist\index.js:47:217)
    at Object.execute (C:\Users\ryuuo\Desktop\S.E.C.R.E.T\Commands\Mod\Clear.js:97:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by RyuuOsamu** [comment]
i am using V14On Feb 7, 2023 1:59 PM, Derock ***@***.***> wrote:
What version of discord.js are you using?

**Comment by ItzDerock** [comment]
Can you run `npm list discord.js` so I can see the exact version you are using?

**Comment by RyuuOsamu** [comment]
^14.7.1

________________________________

**Comment by ItzDerock** [comment]
You're using the wrong function, switch `Transcript.generateFromMessages(...)` to `Transcript.createTranscript(...)`

**Comment by RyuuOsamu** [comment]
Ok i will try thxOn Feb 11, 2023 3:46 AM, Derock ***@***.***> wrote:
You're using the wrong function, switch Transcript.generateFromMessages(...) to Transcript.createTranscript(...)

**Comment by ItzDerock** [comment]
re-open this issue if you are still having issues.
