### ISSUE TITLE
Error while doing transcription (read properties of null)

### ISSUE THREAD

**Issue by MinerPL** [ItzDerock/discord-html-transcripts#135]
A copy of the message from the discord server:

When trying to perform a transcription from a messageDeleteBulk event, a problem pops up reading the author.id value (author is null?)

Error
```js
TypeError: Cannot read properties of null (reading 'id')
    at buildProfiles (C:\Users\MinerPL\IdeaProjects\MightyBot\node_modules\discord-html-transcripts\dist\utils\buildProfiles.js:11:30)
    at renderMessages (C:\Users\MinerPL\IdeaProjects\MightyBot\node_modules\discord-html-transcripts\dist\generator\index.js:63:56)
    at generateFromMessages (C:\Users\MinerPL\IdeaProjects\MightyBot\node_modules\discord-html-transcripts\dist\index.js:43:48)
    at MightyBot.<anonymous> (C:\Users\MinerPL\IdeaProjects\MightyBot\events\logs\messageDeleteBulk.js:14:27)
```

Code
```js
    const transcript = await generateFromMessages(messages.values(), channel, {
        returnType: 'attachment',
        filename: `MessageDeleteBulk-${channel.id}-${Date.now()}.html`,
        footerText: false,
        saveImages: false,
        poweredBy: true,
    });```

* Discord.JS Version: 14.10.2
* NodeJS Version: 18.15.0
* Discord HTML Transcripts Version: 3.1.4
* messages.values() content - https://hastebin.com/share/ifuroyemus.yaml

**Comment by SerenModz21** [comment]
The message author is null when the message is a partial. Since its the messageDeleteBulk event, all you can do is filter out those partial messages. They sadly cannot be fetched because the those messages have already been deleted.
