### ISSUE TITLE
[ExperimentalWarning] When doing a transcript.

### ISSUE THREAD

**Issue by SENPAY98K** [ItzDerock/discord-html-transcripts#149]
`ExperimentalWarning:` buffer.File is an experimental feature and might change at any time
Maybe replacing the used deprecate-features with other alts..

```
(node:12008) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ExperimentalWarning: buffer.File is an experimental feature and might change at any time
    at emitExperimentalWarning (node:internal/util:238:11)
    at new File (node:internal/file:40:5)
    at makeEntry (node:internal/deps/undici/undici:6295:43)
    at FormData.append (node:internal/deps/undici/undici:6207:23)
    at _REST.resolveRequest (D:\MYBOT\node_modules\@discordjs\rest\dist\index.js:1314:20)
    at _REST.queueRequest (D:\MYBOT\node_modules\@discordjs\rest\dist\index.js:1252:46)
    at _REST.request (D:\MYBOT\node_modules\@discordjs\rest\dist\index.js:1218:33)
    at _REST.post (D:\MYBOT\node_modules\@discordjs\rest\dist\index.js:1192:17)
    at TextChannel.send (D:\MYBOT\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:162:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ItzDerock** [comment]
I do not think this is a discord-html-transcripts issue, looking at the stack trace, this comes from `undici` which is called from `@discordjs/rest` and from `discord.js`. I would recommend updating node.js if possible.
