### ISSUE TITLE
Error: Could not parse CSS stylesheet

### ISSUE THREAD

**Issue by vSilva-gb** [ItzDerock/discord-html-transcripts#50]
`Error: Could not parse CSS stylesheet
at exports.createStylesheet (/application/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:34:21)
at HTMLStyleElementImpl._updateAStyleBlock (/application/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
at HTMLStyleElementImpl._childTextContentChangeSteps (/application/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
at TextImpl.replaceData (/application/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:108:23)
at TextImpl.set data [as data] (/application/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:26:10)
at JSDOMParse5Adapter.insertText (/application/node_modules/jsdom/lib/jsdom/browser/parser/html.js:142:22)
at Parser._insertCharacters (/application/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:600:30)
at Object.insertCharacters (/application/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:1062:7)
at Parser._processToken (/application/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:657:55)
at Parser._processInputToken (/application/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:684:18)
at Parser._runParsingLoop (/application/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:440:18)
at Parser.parse (/application/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:344:14)
at Object.parse (/application/node_modules/jsdom/node_modules/parse5/lib/index.js:10:19)
at parseIntoDocument (/application/node_modules/jsdom/lib/jsdom/browser/parser/html.js:202:17)
at parseIntoDocument (/application/node_modules/jsdom/lib/jsdom/browser/parser/index.js:31:10)
at new JSDOM (/application/node_modules/jsdom/lib/api.js:42:5)`

This error occurs after trying to generate a transcript, the transcript is generated normally, but then this error occurs.

**Comment by ItzDerock** [comment]
Doesn't seem to be occurring for me. Are you running the latest version of discord-html-transcripts?

**Comment by vSilva-gb** [comment]
I was using 2.5.8, just upgraded to 2.6.0 to test if it might be fixing the bug, but it didn't.

**Comment by ItzDerock** [comment]
Can you run `npm list jsdom` and send the output?

**Comment by vSilva-gb** [comment]
`D:\Programação\Colorado-Bot>npm list jsdom
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
galdino@2.0.0 D:\Programação\Colorado-Bot
+-- discord-html-transcripts@2.6.0
| `-- jsdom@20.0.0
`-- genius-lyrics-api@3.2.0
  `-- cheerio-without-node-native@0.20.2
    `-- jsdom@7.2.2


D:\Programação\Colorado-Bot>`

**Comment by vSilva-gb** [comment]
I was looking here too, and this error only appeared on the linux system on windows is normal

**Comment by ItzDerock** [comment]
re-open if issue still exists
